// src/routes/dsp/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { base } from '$app/paths';
  import { i18n } from '$lib/i18n/index.svelte';

  let downloadUrl = $state('https://github.com/minseokk77/vesper-dsp/releases/latest');
  let version = $state('');
  let totalDownloads = $state(0);
  let changelog: { version: string; date: string; body: string }[] = $state([]);
  let openChangelog = $state(-1);

  onMount(async () => {
    try {
      // 최신 릴리즈 다운로드 URL 및 버전
      const res = await fetch('https://api.github.com/repos/minseokk77/vesper-dsp/releases?per_page=5');
      const releases = await res.json();

      if (releases.length > 0) {
        const latest = releases[0];
        version = latest.tag_name ?? '';
        const asset = latest.assets?.find((a: { name: string; browser_download_url: string }) =>
          a.name.endsWith('.exe') && !a.name.endsWith('.sig')
        );
        if (asset) downloadUrl = asset.browser_download_url;

        // 누적 다운로드 수 합산
        totalDownloads = releases.reduce((sum: number, rel: { assets: { download_count: number }[] }) =>
          sum + rel.assets.reduce((s: number, a: { download_count: number }) => s + (a.download_count || 0), 0), 0
        );

        // 체인지로그 (최근 3개)
        changelog = releases.slice(0, 3).map((r: { tag_name: string; published_at: string; body: string }) => ({
          version: r.tag_name,
          date: new Date(r.published_at).toLocaleDateString('ko-KR'),
          body: (r.body || '').split('\n').filter((l: string) => l.trim()).slice(0, 4).join('\n')
        }));
      }
    } catch {
      // 폴백 유지
    }
  });
</script>

<svelte:head>
  <title>Vesper DSP - {i18n.t.dspDetail.title}</title>
</svelte:head>

<section class="pt-32 pb-24 px-6 relative z-10 max-w-4xl mx-auto space-y-16">
  <!-- Header -->
  <div class="text-center space-y-4">
    <h1 class="text-5xl md:text-7xl font-semibold tracking-tighter text-[#f5f5f7]">Vesper DSP</h1>
    <p class="text-xl text-[#86868b] tracking-tight">{i18n.t.dspDetail.title}</p>
  </div>

  <!-- Stats Row -->
  <div class="grid grid-cols-3 gap-4">
    <!-- 다운로드 카운터 -->
    <div class="p-6 rounded-[24px] bg-white/[0.02] border border-white/[0.08] backdrop-blur-[60px] text-center">
      <div class="text-3xl font-bold text-indigo-400 mb-1">{totalDownloads > 0 ? totalDownloads.toLocaleString() : '—'}</div>
      <div class="text-xs text-[#86868b]">{i18n.t.dspDetail.totalDownloads}</div>
    </div>
    <!-- 버전 -->
    <div class="p-6 rounded-[24px] bg-white/[0.02] border border-white/[0.08] backdrop-blur-[60px] text-center">
      <div class="text-3xl font-bold text-[#f5f5f7] mb-1">{version || '—'}</div>
      <div class="text-xs text-[#86868b]">Latest Version</div>
    </div>
    <!-- 플랫폼 -->
    <div class="p-6 rounded-[24px] bg-white/[0.02] border border-white/[0.08] backdrop-blur-[60px] text-center">
      <div class="text-3xl font-bold text-[#f5f5f7] mb-1">x64</div>
      <div class="text-xs text-[#86868b]">Windows 10+</div>
    </div>
  </div>

  <!-- Intro -->
  <div class="text-lg md:text-xl text-[#86868b] font-medium leading-relaxed text-center max-w-3xl mx-auto tracking-tight">
    {i18n.t.dspDetail.intro}
  </div>

  <!-- Features Detail -->
  <div class="grid md:grid-cols-2 gap-6">
    <div class="p-10 rounded-[32px] bg-white/[0.02] border border-white/[0.08] shadow-[inset_0_1px_1px_rgba(255,255,255,0.1),0_8px_32px_rgba(0,0,0,0.4)] backdrop-blur-[60px]">
      <h3 class="text-2xl font-semibold tracking-tight text-[#f5f5f7] mb-4">{i18n.t.dspDetail.box1Title}</h3>
      <p class="text-[#86868b] leading-relaxed font-medium text-[17px]">{i18n.t.dspDetail.box1Desc}</p>
    </div>
    <div class="p-10 rounded-[32px] bg-white/[0.02] border border-white/[0.08] shadow-[inset_0_1px_1px_rgba(255,255,255,0.1),0_8px_32px_rgba(0,0,0,0.4)] backdrop-blur-[60px]">
      <h3 class="text-2xl font-semibold tracking-tight text-[#f5f5f7] mb-4">{i18n.t.dspDetail.box2Title}</h3>
      <p class="text-[#86868b] leading-relaxed font-medium text-[17px]">{i18n.t.dspDetail.box2Desc}</p>
    </div>
  </div>

  <!-- System Requirements -->
  <div class="p-8 rounded-[32px] bg-white/[0.02] border border-white/[0.08] backdrop-blur-[60px]">
    <h3 class="text-xl font-semibold text-[#f5f5f7] mb-6">{i18n.t.dspDetail.sysReqTitle}</h3>
    <div class="flex flex-wrap gap-3">
      {#each [['OS', 'Windows 10/11'], ['Architecture', 'x64 (64-bit)'], ['RAM', '4GB+'], ['Runtime', 'VB-Cable HiFi (별도 설치)'], ['Language', 'Rust']] as [label, value]}
        <span class="px-4 py-2 rounded-full bg-white/[0.05] border border-white/[0.08] text-sm text-[#f5f5f7]">
          <span class="text-[#86868b]">{label}:</span> {value}
        </span>
      {/each}
    </div>
  </div>

  <!-- Changelog -->
  <div class="space-y-3">
    <h3 class="text-xl font-semibold text-[#f5f5f7]">{i18n.t.dspDetail.changelogTitle}</h3>
    {#if changelog.length === 0}
      <p class="text-[#86868b] text-sm">{i18n.t.dspDetail.changelogEmpty}</p>
    {:else}
      {#each changelog as entry, idx}
        <button
          onclick={() => openChangelog = openChangelog === idx ? -1 : idx}
          class="w-full p-5 rounded-[24px] bg-white/[0.02] border border-white/[0.08] backdrop-blur-[60px] text-left hover:bg-white/[0.04] transition-all duration-300 block"
        >
          <div class="flex items-center justify-between gap-4">
            <div class="flex items-center gap-3">
              <span class="text-indigo-400 font-semibold">{entry.version}</span>
              <span class="text-[#86868b] text-xs">{entry.date}</span>
            </div>
            <span class="text-[#86868b] text-lg transition-transform duration-300 shrink-0 {openChangelog === idx ? 'rotate-45' : ''}">+</span>
          </div>
          {#if openChangelog === idx}
            <pre class="mt-4 text-[#86868b] text-sm leading-relaxed whitespace-pre-wrap font-sans border-t border-white/[0.06] pt-4">{entry.body}</pre>
          {/if}
        </button>
      {/each}
    {/if}
  </div>

  <!-- Installation Guide -->
  <div class="space-y-4">
    <h3 class="text-xl font-semibold text-[#f5f5f7]">{i18n.t.guide.dspTitle}</h3>
    <div class="space-y-3">
      {#each i18n.t.guide.dspSteps as step}
        <div class="flex gap-5 p-6 rounded-[24px] bg-white/[0.02] border border-white/[0.08] backdrop-blur-[60px]">
          <div class="w-8 h-8 rounded-full bg-indigo-500/20 border border-indigo-500/30 flex items-center justify-center shrink-0 text-indigo-400 font-bold text-sm">
            {step.step}
          </div>
          <div>
            <h4 class="text-[#f5f5f7] font-semibold mb-1 text-[15px]">{step.title}</h4>
            <p class="text-[#86868b] leading-relaxed text-sm">{step.desc}</p>
          </div>
        </div>
      {/each}
    </div>
  </div>

  <!-- Download -->
  <div class="flex flex-col items-center gap-3 pt-4">
    <a href={downloadUrl} download class="px-10 py-4 rounded-full bg-[#f5f5f7] text-black font-semibold text-[15px] tracking-wide hover:scale-105 active:scale-95 transition-transform flex items-center gap-2">
      <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
      </svg>
      {i18n.t.dspDetail.downloadBtn}
    </a>
    {#if version}
      <span class="text-xs text-[#86868b]">{version}</span>
    {/if}
  </div>
</section>

// app/dsp/page.tsx
"use client";

import { useEffect, useState } from "react";
import { Navbar } from "../components/Navbar";
import { Footer } from "../components/Footer";

export default function DSPPage() {
  const [downloadUrl, setDownloadUrl] = useState("https://github.com/minseokk77/vesper-dsp/releases/latest");
  const [version, setVersion] = useState("");
  const [totalDownloads, setTotalDownloads] = useState(0);
  const [changelog, setChangelog] = useState<{ version: string; date: string; body: string }[]>([]);
  const [openChangelog, setOpenChangelog] = useState(-1);

  useEffect(() => {
    async function fetchReleases() {
      try {
        const res = await fetch("https://api.github.com/repos/minseokk77/vesper-dsp/releases?per_page=5");
        const releases = await res.json();

        if (releases.length > 0) {
          const latest = releases[0];
          setVersion(latest.tag_name ?? "");
          const asset = latest.assets?.find(
            (a: { name: string; browser_download_url: string }) =>
              a.name.endsWith(".exe") && !a.name.endsWith(".sig")
          );
          if (asset) setDownloadUrl(asset.browser_download_url);

          const total = releases.reduce(
            (sum: number, rel: { assets: { download_count: number }[] }) =>
              sum +
              rel.assets.reduce(
                (s: number, a: { download_count: number }) => s + (a.download_count || 0),
                0
              ),
            0
          );
          setTotalDownloads(total);

          const cl = releases.slice(0, 3).map((r: { tag_name: string; published_at: string; body: string | null }) => ({
            version: r.tag_name,
            date: new Date(r.published_at).toLocaleDateString("ko-KR"),
            body: (r.body || "")
              .split("\n")
              .filter((l: string) => l.trim())
              .slice(0, 4)
              .join("\n"),
          }));
          setChangelog(cl);
        }
      } catch {
        // ignore
      }
    }
    fetchReleases();
  }, []);

  return (
    <>
      <div style={{ position: 'sticky', top: 0, zIndex: 50 }}>
        <Navbar />
      </div>

      <main className="pt-32 pb-24 px-6 relative z-10 max-w-4xl mx-auto space-y-16">
        <div className="text-center space-y-4">
          <h1 className="text-5xl md:text-7xl font-semibold tracking-tighter text-[#f5f5f7]">Vesper DSP</h1>
          <p className="text-xl text-[#86868b] tracking-tight">헤드폰 및 스피커 보정 시스템</p>
        </div>

        <div className="grid grid-cols-3 gap-4">
          <div className="p-6 rounded-[24px] bg-white/[0.02] border border-white/[0.08] backdrop-blur-[60px] text-center">
            <div className="text-3xl font-bold text-blue-400 mb-1">
              {totalDownloads > 0 ? totalDownloads.toLocaleString() : "—"}
            </div>
            <div className="text-xs text-[#86868b]">누적 다운로드</div>
          </div>
          <div className="p-6 rounded-[24px] bg-white/[0.02] border border-white/[0.08] backdrop-blur-[60px] text-center">
            <div className="text-3xl font-bold text-[#f5f5f7] mb-1">{version || "—"}</div>
            <div className="text-xs text-[#86868b]">최신 버전</div>
          </div>
          <div className="p-6 rounded-[24px] bg-white/[0.02] border border-white/[0.08] backdrop-blur-[60px] text-center">
            <div className="text-3xl font-bold text-[#f5f5f7] mb-1">x64</div>
            <div className="text-xs text-[#86868b]">Windows 10+</div>
          </div>
        </div>

        <div className="text-lg md:text-xl text-[#86868b] font-medium leading-relaxed text-center max-w-3xl mx-auto tracking-tight">
          시스템 전역에서 작동하는 고정밀 오디오 보정 도구.
          당신의 장비가 가진 본연의 소리를 정확하게 이끌어냅니다.
        </div>

        <div className="space-y-3">
          <h3 className="text-xl font-semibold text-[#f5f5f7]">최근 업데이트</h3>
          {changelog.length === 0 ? (
            <p className="text-[#86868b] text-sm">로딩 중...</p>
          ) : (
            changelog.map((entry, idx) => (
              <button
                key={idx}
                onClick={() => setOpenChangelog(openChangelog === idx ? -1 : idx)}
                className="w-full p-5 rounded-[24px] bg-white/[0.02] border border-white/[0.08] backdrop-blur-[60px] text-left hover:bg-white/[0.04] transition-all duration-300 block"
              >
                <div className="flex items-center justify-between gap-4">
                  <div className="flex items-center gap-3">
                    <span className="text-blue-400 font-semibold">{entry.version}</span>
                    <span className="text-[#86868b] text-xs">{entry.date}</span>
                  </div>
                  <span className={`text-[#86868b] text-lg transition-transform duration-300 shrink-0 ${openChangelog === idx ? "rotate-45" : ""}`}>
                    +
                  </span>
                </div>
                {openChangelog === idx && (
                  <pre className="mt-4 text-[#86868b] text-sm leading-relaxed whitespace-pre-wrap font-sans border-t border-white/[0.06] pt-4">
                    {entry.body}
                  </pre>
                )}
              </button>
            ))
          )}
        </div>

        <div className="flex flex-col items-center gap-3 pt-4">
          <a
            href={downloadUrl}
            className="px-10 py-4 rounded-full bg-[#f5f5f7] text-black font-semibold text-[15px] tracking-wide hover:scale-105 active:scale-95 transition-transform flex items-center gap-2"
          >
            Vesper DSP 다운로드
          </a>
          {version && <span className="text-xs text-[#86868b]">{version}</span>}
        </div>
      </main>
      <Footer />
    </>
  );
}
